language: python

python:
    - "2.7"

# command to install dependencies
install:
    - python setup.py install

# command to run tests
script:
    - python setup.py test
    - pip install coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)
