# (c) Copyright 2017 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Zing stats infra consisting of two containers, a generator for
# retrieving the data and creating the reports, and a web server
# for serving them. Uses a named volume for sharing the data between
# containers.

version: '3'

services:
  zing-stats-web:
    image: nginx:stable-alpine
    ports:
      - '8172:80'
    volumes:
      - zing-stats:/usr/share/nginx/html:ro

  zing-stats:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - GERRIT_URL
      - GITHUB_URL
      - GITHUB_TOKEN

    volumes:
      - zing-stats:/var/www/html:rw
      - ${ZING_PROJECTS}:/projects.json:ro
    restart: always

volumes:
  zing-stats:
