#!/bin/bash
#
# (c) Copyright 2018 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# docker automated builds sets a number of env vars including
#  SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
#  DOCKER_REPO: the name of the Docker repository being built.
# https://docs.docker.com/docker-cloud/builds/advanced/#environment-variables-for-building-and-testing

docker build --build-arg VERSION="$SOURCE_BRANCH" -t "$DOCKER_REPO:$SOURCE_BRANCH" -t "$DOCKER_REPO:latest" .
